[project]
name = "torchrua"
version = "0.5.1"
description = "Rua your variable-length tensors!"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch",
]

[dependency-groups]
dev = [
    "hypothesis>=6.140.3",
    "pytest>=8.4.2",
    "torchnyan>=0.1.3",
]
